plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', rootProject.project(':common').file('src/generated/resources/').getAbsolutePath(),
                    '--existing', rootProject.project(':common').file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories{
    maven {
        url "https://cursemaven.com"
    }
}

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    modImplementation("curse.maven:apothic-attributes-898963:5340012")
    modImplementation("curse.maven:combat-roll-678036:5625925")

    modImplementation("curse.maven:playeranimator-658587:4587214")
    modImplementation("curse.maven:cloth-config-348521:5729105")
    modImplementation("curse.maven:placebo-283644:6274231")

    modImplementation("curse.maven:paragliders-289240:5046069")

    modImplementation("curse.maven:better-paragliders-895261:5805065")

    modImplementation("curse.maven:sword-blocking-mechanics-969424:6043941")

    modImplementation("maven.modrinth:better-combat:${project.better_combat_version}-forge")
    modImplementation("curse.maven:puzzles-lib-495476:6918565")

    modImplementation("curse.maven:terramity-1084134:6054971")

    // Better Combat Dependencies
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${project.mixin_extras_version}"))


    // Compile against only the API artifact
    modCompileOnly("top.theillusivec4.curios:curios-forge:${curios_version}:api")
    // Use the full Curios API jar at runtime
    modRuntimeOnly("top.theillusivec4.curios:curios-forge:${curios_version}")

    modImplementation("software.bernie.geckolib:geckolib-forge-$minecraft_version:$geckolib")

}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}
